### ISSUE TITLE
v2: Agent App - to show/hide Topup and Outstanding menu in the home page 

### ISSUE THREAD

**Issue by chencc1800** [zsuperxtreme/gd#116]
1. check agent type when agent login, api: http://api.gdlotto.tl/json/loginAgent.aspx
2. parameter "agentType": MA, KA, PA, AG
3. agentType:MA, KA - show Topup menu and hide Outstanding menu
4. agentType:PA - show Outstanding menu and hide Topup menu
5. agentType:AG - show both Outstanding menu and Topup menu

**Comment by zsuperxtreme** [comment]
What MA,KA & PA stand for?
