### ISSUE TITLE
result not showed out in Winning Jackpot

### ISSUE THREAD

**Issue by chencc1800** [zsuperxtreme/gd#23]
sample data:
{"status":"1","orderID":"0000000000000001","dateTime":"Nov 27 2021
9:22AM","total":438,"jackpots":[{"drawDate":"2018-02-15", "bonusType":"Small Bonus", "unit":"2.000000", "number":"6736",
"winning":"438.000000", "pageNum":"0"}]}

<img width="1406" alt="Screenshot 2021-11-27 at 8 21 28 AM" src="https://user-images.githubusercontent.com/94815470/143662368-50ba56eb-7272-4265-bc74-934597b5f30e.png">
<img width="984" alt="Screenshot 2021-11-27 at 8 22 40 AM" src="https://user-images.githubusercontent.com/94815470/143662373-589c11ca-82d0-472b-a6ae-fdfcbd50371e.png">

**Comment by zsuperxtreme** [comment]
No changes - test all works
